name: ImageAnalysisDemo
dependencies:
  - python=3.7
  - conda-forge::jupyter==1.0.0
  - matplotlib==3.5.1
  - numpy>=1.21.0
  - scikit-image>=0.19.0
  - conda-forge::itk>=5.2.0
  - conda-forge::itkwidgets>=0.32.0
  - conda-forge::ipydatawidgets==4.2.0
  - tqdm>=4.50.0
  - pandas>=1.3.0
  - openpyxl>=3.0.0
  - imagecodecs>=2020.12.22
  - pip
  - pip:
      nbgitpuller